blank_issues_enabled: false
contact_links:
  - name: quarto_titlepages Discussion board
    url: https://github.com/nmfs-opensci/quarto_titlepages/discussions
    about: Please ask and answer questions here.
